from __future__ import annotations

from typing import Dict

MAX_AUDIO_BYTES = 25 * 1024 * 1024
DEFAULT_HOST = "127.0.0.1"
DEFAULT_PORT = "8765"
DEFAULT_AUDIO_CHUNK_MS = "2200"
DEFAULT_WHISPER_MODEL = "base"
DEFAULT_WHISPER_DEVICE = "cpu"
DEFAULT_WHISPER_COMPUTE_TYPE = "int8"
DEFAULT_TRANSCRIPTION_BACKEND = "google"
DEFAULT_WHISPER_LOCAL_FILES_ONLY = "1"
DEFAULT_ARGOS_CHUNK_TYPE = "MINISBD"
DEFAULT_TRANSLATION_BACKEND = "google"
DEFAULT_LIBRETRANSLATE_URL = "http://127.0.0.1:5000"
DEFAULT_LIBRETRANSLATE_TIMEOUT_SEC = "15"

DEFAULT_SETTINGS: Dict[str, str] = {
    "APP_HOST": DEFAULT_HOST,
    "APP_PORT": DEFAULT_PORT,
    "APP_OPEN_BROWSER": "1",
    "AUDIO_CHUNK_MS": DEFAULT_AUDIO_CHUNK_MS,
    "WHISPER_MODEL": DEFAULT_WHISPER_MODEL,
    "WHISPER_DEVICE": DEFAULT_WHISPER_DEVICE,
    "WHISPER_COMPUTE_TYPE": DEFAULT_WHISPER_COMPUTE_TYPE,
    "TRANSCRIPTION_BACKEND": DEFAULT_TRANSCRIPTION_BACKEND,
    "WHISPER_LOCAL_FILES_ONLY": DEFAULT_WHISPER_LOCAL_FILES_ONLY,
    "ARGOS_CHUNK_TYPE": DEFAULT_ARGOS_CHUNK_TYPE,
    "AUTO_INSTALL_TRANSLATION_PACKAGES": "1",
    "TRANSLATION_BACKEND": DEFAULT_TRANSLATION_BACKEND,
    "LIBRETRANSLATE_URL": DEFAULT_LIBRETRANSLATE_URL,
    "LIBRETRANSLATE_API_KEY": "",
    "LIBRETRANSLATE_TIMEOUT_SEC": DEFAULT_LIBRETRANSLATE_TIMEOUT_SEC,
}

MAIN_LOG_FILE = "alberttranslator.log"
FATAL_LOG_FILE = "alberttranslator_fatal.log"
